components/Posts/Filter/index.js
components/Posts/index.jsx
package.json
pages/[slug].js
pages/_app.js
pages/tags/[tagID].js

provide apollo client to the components

---

.github/workflows/deploy.yml
terraform/main.tf
terraform/variables.tf

Adding the NEXT_PRIVATE_HUBSPOT_API_KEY environment variable.
please add repository secrets:
* staging_hubspot_api_key
* production_hubspot_api_key

feat(terraform): add NEXT_PRIVATE_HUBSPOT_API_KEY environment variable

---

components/Footer/FooterBottomBar/index.jsx
pages/privacy-policy.js

- add privacy policy link and page
- add terms and conditions link
- use vertical layout for footer links on mobile
- add margin-bottom to allow room for the overlapping intercom message button

feat(site): add privacy-policy page

---

pages/terms.js

import terms page from the old repository

feat: terms page #169

---

.github/workflows/deploy.yml
terraform/main.tf

Add new path for /docs -> docs.amplication.com

add path /docs

---

components/Posts/PostCard/index.jsx
components/Posts/PostHot/index.js
pages/blog.js
pages/blog/[slug].js
pages/tags/[tagID].js

remove the blog content from the __NEXT_DATA__ element in pages that don't need it

reduce page size

---

components/Header/Menu/index.jsx
package-lock.json

Improve the UX by adding the hover effect on the links oh header

added hover effect on links

---

lib/rss/index.js
package-lock.json
package.json
pages/blog/feed.js
pages/tags/[tagID]/feed.js

Dependent on #217 to get content of blog posts.

feat(rss): generate rss feed for blog content

---

pages/index.js

close: amplication/amplication#4146
**Result:**

Add twitter preview card

---

components/Sections/MainPage/Roadmap/index.jsx
public/styles/style.css

closes [#4075](https://github.com/amplication/amplication/issues/4075)
- Add padding to roadmap section
- Update line height

fix: Roadmap padding in mobile view

---

components/Header/Menu/index.jsx

close: amplication/amplication#4174
https://user-images.githubusercontent.com/80192140/196087145-030538c8-6601-4be1-bf1e-8cfeba20ceb6.mp4

Close Navbar menu after clicking links

---

components/Sections/Team/TeamBlock/index.jsx

Update team members

---

components/Sections/Team/TeamBlock/index.jsx

naim -> Naim

---

next.config.js
package-lock.json
package.json

feat(css): add critical css

---

next.config.js
pages/blog/[slug].js

feat(meta): support alternative titles and descriptions for SEO

---

pages/enterprise.js

fix(enterprise): fix enterprise title

---

pages/enterprise.js

update ee meta title

---

pages/_app.js

fix(Intercom): fix Intercom

---

next.config.js

fix(redirect): add blog redirect

---

next.config.js

Reverts amplication/amplication-site#266

Revert "fix(redirect): add blog redirect"

---

components/Sections/MainPage/Roadmap/index.jsx

check mongo on road map

---

components/Sections/About/LowCode/index.jsx
components/Sections/Community/Champions/index.jsx
components/Sections/Community/Support/index.jsx
components/Sections/MainPage/HeroBlock/index.jsx
pages/features.js

update discord link

---

public/styles/style.css

AMPLBLG-58 fix hero section height

---

layouts/main.js
package-lock.json
package.json

feat(testimonial): add testimonials component

---

components/Posts/TOC/index.jsx
components/Posts/TOC/style.module.css
helpers/index.js
pages/blog/[slug].js

fix(blog): remove code demoting headings and fix descriptions

---

components/Posts/PostCard/index.jsx
components/Posts/PostHot/index.jsx
lib/rss/index.js
pages/blog.js
pages/blog/[slug].js
pages/blog/feed.js
pages/tags/[tagSlug].js
pages/tags/[tagSlug]/feed.js

feat(blog): use `publishedAt` for date

---

pages/_app.js
pages/blog/[slug].js
styles/globals.css
tailwind.config.js

update blog style for readability

---

content/sla.md
next.config.js
package-lock.json
package.json
pages/sla.js

Closes: [amplication/amplication#[issue-number]](https://github.com/amplication/amplication/issues/5072)
add a new SLA page at /sla

Add SLA page

---

components/Sections/About/HeroBlock/index.jsx
components/Sections/About/LogoList/index.jsx
components/Sections/About/UsersList/index.jsx
pages/about.js
pages/blog.js
pages/privacy-policy.js
pages/team.js
pages/testimonials.js

Fixes: https://github.com/amplication/amplication/issues/5450

feat:update titles

---

components/Header/index.jsx

Fixes: https://github.com/amplication/amplication/issues/5626

feat:revert top bar

---

components/Sections/Enterprise/Hero/index.jsx

Fixes: amplication/amplication#5920

fix mixed events

---

pages/blog/[slug].js

feat(twitter): add authors twitter handles to head

---

components/Posts/PostCard/Tags/index.jsx
pages/blog/[slug].js

feat(tags): add links to tag chips

---

pages/_app.js

remove google tag manager

---

netlify.toml

Fixes: amplication/amplication-infrastructure-next#208

chore: add netlify redirect configuration

---

components/Posts/PostCard/Tumbnail/index.jsx
components/Posts/Skeleton/index.jsx

style: fix blog thumbnail ratio

---

components/Common/HubSpotForm/index.jsx
components/Common/SubscribeForm/index.jsx
components/Sections/DbImportBeta/Form/index.jsx
pages/contact-us.js

feat add event on form submission

---

pages/testimonials.js

update testimonials source

---

components/Plugins/plugins-panel.jsx
styles/carousel.css

style: fix plugins carousel

---

components/Footer/FooterBottomBar/index.jsx

Fixes: amplication/amplication#7116
This PR will fix `follow-us` alignment

fix: follow-us alignment

---

components/Sections/Hacktoberfest/Hero/redeem-coupon.jsx
pages/hacktoberfest-2023/rewards/[slug].js

update reward page content

---

components/Common/Button/index.jsx
components/Common/GitHubStarsButton/GitHubStarsUsButtonContent.jsx
components/Common/GitHubStarsButton/index.jsx
components/Header/Menu/index.jsx
components/Sections/MainPage/HeroBlock/index.jsx
public/styles/style.css
styles/bootstrap-wrapper.scss

feat: add star us button on header v2

---

components/Sections/Team/TeamBlock/index.jsx

update team page

---

components/Sections/Pricing/HeroBlock/index.jsx
components/Sections/Pricing/PromoBanner/index.jsx
pages/pricing.js
styles/stigg.css

feat: pricing banner

---

components/Header/index.jsx

update top banner

---

styles/stigg.css

fix(css): support 2 or 3 plans width dynamically

---

styles/stigg.css

style:fix pricing on mobile

---

pages/pricing.js

(fix): Fixing the mispelled title which could affect SEO.

Fix: Pricing Page Title

---

components/Header/TopBar/enterpriseTrial.jsx
components/Header/index.jsx
components/Sections/About/StartNow/index.jsx
components/Sections/Enterprise/Hero/index.jsx
components/Sections/Enterprise/HeroBlock/index.jsx
components/Sections/MainPage/HeroBlock/index.jsx
components/Sections/Modernization/Hero/index.jsx
components/Sections/Pricing/PricingPlans/index.jsx

update content for the enteprise trial

---

pages/_app.js

Fixes: https://github.com/amplication/amplication-cluster-configuration/issues/147

chore: migrate to amplication analytics configuration

---

pages/plugins.js

style:plugin list

---

components/Common/HubSpotForm/index.jsx
components/Sections/CodeSmartPlayHard/Confirmed/index.jsx
components/Sections/CodeSmartPlayHard/Form/index.jsx
pages/code-smart-play-hard.js

update raffle page

---

components/Sections/BreakTheMonolith/Hero/index.jsx

chore(website): update BTM LP text

---

components/Sections/BreakTheMonolith/Hero/index.jsx

Update the BTM message

---

components/Header/TopBar/enterpriseTrial.jsx
components/Sections/CodeSmartPlayHard/Confirmed/index.jsx

Fixes: https://github.com/amplication/private-issues/issues/162

chore(website): update trial length to 7 days

---

components/Common/HubSpotForm/index.jsx
components/Sections/CodeSmartPlayHard/Form/index.jsx
components/Sections/CodeSmartPlayHard/Hero/index.jsx

feat:kubecon raffle

---

components/Sections/CodeSmartPlayHard/Form/index.jsx

fix: email field

---

components/Sections/CodeSmartPlayHard/Form/index.jsx

feat: update form id

---

components/Common/PageHero/index.jsx

fix:hero button

---

components/Sections/Enterprise/Testimonials/index.jsx

feat:update testimonials on HP

---

components/Footer/FooterBottomBar/index.jsx
components/Footer/FooterLinks/index.jsx
components/Footer/index.jsx
components/Header/Menu/menu-items.js
pages/customers.js
pages/plugins.js
tailwind.config.js

Feat: add footer

---

components/Header/TopBar/productHunt.jsx
components/Header/index.jsx
tailwind.config.js

feat:add product hunt banner

---

pages/jovu--production-ready-ai-code-generation.js

(update): Changing the link from the home page of the docs to the Amplication AI page.

Update Jovu Page Docs Link

---

pages/jovu--production-ready-ai-code-generation.js

fix hero title

---

components/Sections/Pricing/PricingPlans/index.jsx

update pricing plan titles

---

components/Common/CtaBanner/index.jsx

chore(blog): update blog CTA banner texts and url
